
# 廠商後台測試環境: https://cweb.pay2go.com
# 信用卡測試卡號:
# 4000-2222-2222-2222
# 4000-1322-2222-2222
default: &default
  merchant_id: 32513518
  hash_key: 1eufhGdO0YAIZxE6hpugWScmaZRQ5Pz7
  hash_iv: 33mlKA9LzJtyh8Fz
  url: https://capi.pay2go.com/MPG/mpg_gateway
  notify_url: 'http://zenpractice5022.cloudapp.net/users/1/orders'

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default